//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SOAPWebServiceConnector.BLZWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BLZServiceSOAP11Binding", Namespace="http://thomas-bayer.com/blz/")]
    public partial class BLZService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getBankOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BLZService() {
            this.Url = global::SOAPWebServiceConnector.Properties.Settings.Default.SOAPWebServiceConnector_BLZWebService_BLZService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getBankCompletedEventHandler getBankCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://thomas-bayer.com/blz/", ResponseNamespace="http://thomas-bayer.com/blz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("details")]
        public detailsType getBank(string blz) {
            object[] results = this.Invoke("getBank", new object[] {
                        blz});
            return ((detailsType)(results[0]));
        }
        
        /// <remarks/>
        public void getBankAsync(string blz) {
            this.getBankAsync(blz, null);
        }
        
        /// <remarks/>
        public void getBankAsync(string blz, object userState) {
            if ((this.getBankOperationCompleted == null)) {
                this.getBankOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBankOperationCompleted);
            }
            this.InvokeAsync("getBank", new object[] {
                        blz}, this.getBankOperationCompleted, userState);
        }
        
        private void OngetBankOperationCompleted(object arg) {
            if ((this.getBankCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBankCompleted(this, new getBankCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thomas-bayer.com/blz/")]
    public partial class detailsType {
        
        private string bezeichnungField;
        
        private string bicField;
        
        private string ortField;
        
        private string plzField;
        
        /// <remarks/>
        public string bezeichnung {
            get {
                return this.bezeichnungField;
            }
            set {
                this.bezeichnungField = value;
            }
        }
        
        /// <remarks/>
        public string bic {
            get {
                return this.bicField;
            }
            set {
                this.bicField = value;
            }
        }
        
        /// <remarks/>
        public string ort {
            get {
                return this.ortField;
            }
            set {
                this.ortField = value;
            }
        }
        
        /// <remarks/>
        public string plz {
            get {
                return this.plzField;
            }
            set {
                this.plzField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getBankCompletedEventHandler(object sender, getBankCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBankCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBankCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public detailsType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((detailsType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591